# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Playwright Tests
on: 
  workflow_dispatch:
    
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright
        playwright install
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Setup .env variables
      env:
        SECRET_USR: ${{secrets.USER_NAME}}
        SECRET_PWD: ${{secrets.PWD}}
      run: |
        pwd
        echo "USERNAME=$SECRET_USR" > ../../.env
        echo "PWD=$SECRET_PWD" >> ../../.env
    - name: Run your tests
      run: pytest
    
